#!/bin/bash
#SBATCH --job-name=BEC
#SBATCH --gres=gpu:2
#SBATCH --mem=40G
#SBATCH --nodes=1
#SBATCH --time=1-0:00:00 
#SBATCH --mail-type=begin,end,fail,requeue 
#SBATCH --export=all 
#SBATCH --out=BEC-%j.out
 
echo "State training the model "
echo "==="*50 

python run_data.py --config config/Ex1.py
python run_model.py --config config/Ex1.py --train 

echo "==="*50 
echo "End training the model "

